# Welcome to Jekyll!
title: Online &hearts; Resume
url:
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: en                    # html lang
open: true                  # open or close your site
date_format: "%Y-%m-%d"     # date format
google_analytics:           # your google analytics
cloudflare_analytics:       # your cloudflare analytics
allow_search_engines: true  # allow search engines indexing your resume
theme_color: "#1DA1F2"      # your favorite theme color
